// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8GwG2b4X4U1RBhFjGr_tN_JuZEH1tXZs',
    appId: '1:99657294417:web:ed8a2b223682a5bea64e70',
    messagingSenderId: '99657294417',
    projectId: 'flutterppkd',
    authDomain: 'flutterppkd.firebaseapp.com',
    storageBucket: 'flutterppkd.firebasestorage.app',
    measurementId: 'G-9LTX8V6M7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2sU1GE5GgieUdu9Do3KOkMJLpogMTQPc',
    appId: '1:99657294417:android:c957551304d9c971a64e70',
    messagingSenderId: '99657294417',
    projectId: 'flutterppkd',
    storageBucket: 'flutterppkd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJbj2A1WW_YNskox44o1_DfbEsF5o7DsQ',
    appId: '1:99657294417:ios:f80bd70ba762ac12a64e70',
    messagingSenderId: '99657294417',
    projectId: 'flutterppkd',
    storageBucket: 'flutterppkd.firebasestorage.app',
    iosBundleId: 'com.example.firebaseflutterppkd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJbj2A1WW_YNskox44o1_DfbEsF5o7DsQ',
    appId: '1:99657294417:ios:f80bd70ba762ac12a64e70',
    messagingSenderId: '99657294417',
    projectId: 'flutterppkd',
    storageBucket: 'flutterppkd.firebasestorage.app',
    iosBundleId: 'com.example.firebaseflutterppkd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8GwG2b4X4U1RBhFjGr_tN_JuZEH1tXZs',
    appId: '1:99657294417:web:0abf776165a59337a64e70',
    messagingSenderId: '99657294417',
    projectId: 'flutterppkd',
    authDomain: 'flutterppkd.firebaseapp.com',
    storageBucket: 'flutterppkd.firebasestorage.app',
    measurementId: 'G-LEHCFVKK8K',
  );
}
